services:
  adk-voice-agent:
    build: .
    container_name: adk-voice-agent
    expose:
      - "8000"  
    volumes:
      - ./app/credentials.json:/app/app/credentials.json
      - ./.credentials:/root/.credentials
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - adk-voice-agent
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
